import { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Search } from 'lucide-react';
import { AgentAssetData, AgentAppType } from '@/types/project';
import { FileSystemBrowser } from '@/components/workspace/FileSystemBrowser';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { MOCK_AGENT_ASSETS } from '@/data/mockProject';

export default function AssetsPage() {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedAgentFilter, setSelectedAgentFilter] = useState<AgentAppType | 'all'>('all');

  // Filter assets
  const filteredAssets = useMemo(() => {
    let filtered = [...MOCK_AGENT_ASSETS];

    // Filter by agent
    if (selectedAgentFilter !== 'all') {
      filtered = filtered.filter(asset => asset.agent.type === selectedAgentFilter);
    }

    // Filter by search query
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(asset => 
        asset.title.toLowerCase().includes(query) ||
        asset.sourceContext.toLowerCase().includes(query) ||
        asset.agent.name.toLowerCase().includes(query)
      );
    }

    // Sort by pinned first, then by date
    return filtered.sort((a, b) => {
      if (a.isPinned !== b.isPinned) {
        return a.isPinned ? -1 : 1;
      }
      return b.createdAt.getTime() - a.createdAt.getTime();
    });
  }, [selectedAgentFilter, searchQuery]);

  const handleTrace = (conversationId: string, messageId: string) => {
    navigate(`/chat?msg_id=${messageId}`);
  };

  const handleRemix = (asset: AgentAssetData) => {
    navigate(`/chat?remix=${asset.id}`);
  };

  const handleSave = (asset: AgentAssetData) => {
    console.log('Save asset:', asset);
  };

  const handlePin = (assetId: string, pinned: boolean) => {
    console.log('Pin asset:', assetId, pinned);
  };

  return (
    <div className="h-screen flex flex-col bg-[#FAFAFA]">
      {/* Header */}
      <header className="pt-12 pb-6 px-6 border-b border-stone-200 bg-white">
        <div className="max-w-[1600px] mx-auto">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-4">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => navigate('/')}
                className="gap-2"
              >
                <ArrowLeft size={16} />
                Back to Project
              </Button>
              <div>
                <h1 className="font-serif font-bold text-4xl text-stone-900">
                  All Assets
                </h1>
                <p className="text-sm text-stone-500 mt-1">
                  Browse and manage all assets generated by Agents
                </p>
              </div>
            </div>
          </div>

          {/* Search and Filters */}
          <div className="flex items-center gap-4">
            <div className="flex-1 max-w-md">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-stone-400" size={18} />
                <Input
                  type="search"
                  placeholder="Search assets..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 bg-white border-stone-200"
                />
              </div>
            </div>

            {/* Agent Filter Chips */}
            <div className="flex items-center gap-2">
              {(['all', 'framia', 'hunter', 'enter', 'combos'] as const).map((agent) => (
                <button
                  key={agent}
                  onClick={() => setSelectedAgentFilter(agent)}
                  className={`
                    px-3 py-1.5 rounded-full text-xs font-medium transition-all whitespace-nowrap
                    ${
                      selectedAgentFilter === agent
                        ? 'bg-orange-100 text-orange-700 border border-orange-200'
                        : 'bg-white text-stone-600 border border-stone-200 hover:bg-stone-50'
                    }
                  `}
                >
                  {agent === 'all' ? 'All' : agent.charAt(0).toUpperCase() + agent.slice(1)}
                </button>
              ))}
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 overflow-hidden">
        <div className="h-full max-w-[1600px] mx-auto p-6">
          <div className="h-full">
            <FileSystemBrowser
              assets={filteredAssets}
              onTrace={handleTrace}
              onRemix={handleRemix}
              onSave={handleSave}
              onPin={handlePin}
            />
          </div>
        </div>
      </main>
    </div>
  );
}

